const express=require('express')
const mongoose=require('mongoose')
const config=require('./utils/config')
const logger=require('./utils/logger')
const blogPostRouter=require('./controller/blog')
const app=express()
mongoose.connect(config.MONGODB_URI)
app.use(express.json())
app.use('/api/blogs',blogPostRouter)
module.exports=app
